### ISSUE TITLE
在"路径配置验证器"裡使用"固定标签"或"基于路径的动态标签"時報錯

### ISSUE THREAD

**Issue by bennyz327** [anobaka/InsideWorld#192]
因為和另一篇#191 的問題是可以獨立觸發的，不確定是否為相同原因，故分開成另一個Issue
請大老檢查看看

測試目錄結構如下

> 

    |--媒体库選擇的根目录
      |--2022
         |--[日期]名稱.zip
         |--[日期]名稱.zip 
         |--[日期]名稱.zip   
         |--[日期]名稱.zip
         |--更多的zip..
      |--2021
         |--[日期]名稱
               |--1.mp4
               |--2.mp4
         |--[日期]名稱.zip
         |--更多的zip..
      |--2019
         |--[日期]名稱.zip
         |--更多的zip..
      |--2018
         |--[日期]名稱.zip
         |--更多的zip..

A
選擇第二層作為資源，不使用增強器
設定1個自訂標籤作為"固定標籤"
點選同步會報錯

B
選擇第二層作為資源，不使用增強器
勾選"基于路径的动态标签"中的"使用资源路径前的第1层"
點選同步會報錯

版本
1.6.1-beta

2種報錯的Log是一樣的
MediaLibraryService:Sync
message: An error occurred while saving the entity changes. See the inner exception for details.
stacktrace:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Bootstrap.Components.Orm.Infrastructures.BaseService`1.AddRange[TResource](IEnumerable`1 resources) in E:\Anobaka\LazyMortal\src\Bootstrap\Components\Orm\Infrastructures\BaseService.cs:line 277
   at Bootstrap.Components.Orm.FullMemoryCacheResourceService`3.AddRange(List`1 resources) in E:\Anobaka\LazyMortal\src\Bootstrap\Components\Orm\FullMemoryCacheResourceService.cs:line 0
   at Bakabase.InsideWorld.Business.Services.ResourceTagMappingService.UpdateRange(Dictionary`2 resourceTagMappings) in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Services\ResourceTagMappingService.cs:line 38
   at Bakabase.InsideWorld.Business.Services.MediaLibraryService.Sync(BackgroundTask task) in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Services\MediaLibraryService.cs:line 398
   at Bakabase.InsideWorld.Business.Services.MediaLibraryService.<>c.<<SyncInBackgroundTask>b__25_0>d.MoveNext() in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Services\MediaLibraryService.cs:line 103
--- End of stack trace from previous location ---
   at Bakabase.InsideWorld.Business.Components.Tasks.BackgroundTaskHelper.<>c__DisplayClass7_0`1.<<RunInNewScope>b__0>d.MoveNext() in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\Tasks\BackgroundTaskHelper.cs:line 62
--- End of stack trace from previous location ---
   at Bakabase.InsideWorld.Business.Components.Tasks.BackgroundTaskHelper.<>c__DisplayClass7_0`1.<<RunInNewScope>b__0>d.MoveNext() in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\Tasks\BackgroundTaskHelper.cs:line 62
--- End of stack trace from previous location ---
   at Bakabase.InsideWorld.Business.Components.Tasks.BackgroundTaskManager.<>c__DisplayClass10_0.<<RunInBackground>b__1>d.MoveNext() in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\Tasks\BackgroundTaskManager.cs:line 130
inner1 message: SQLite Error 19: 'UNIQUE constraint failed: ResourceTagMappings.TagId, ResourceTagMappings.ResourceId'.
inner1 stacktrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

**Comment by anobaka** [comment]
v1.6.1-beta2已发布，可以一键更新
