### ISSUE TITLE
Cookie讀取問題

### ISSUE THREAD

**Issue by bennyz327** [anobaka/InsideWorld#267]
大老可以請教一下，cookie如何正確讓inside world讀取呢?
我網頁可以正常瀏覽exhentai，試過用餅乾提取器、F12裡面直接複製貼上，都無法讓inside world成功讀取到餅乾
有甚麼特定的格式嗎?
(錯誤訊息都是"message: Cookie is not set")

**Comment by anobaka** [comment]
感谢您的反馈

> 我網頁可以正常瀏覽exhentai，試過用餅乾提取器、F12裡面直接複製貼上，都無法讓inside world成功讀取到餅乾

看起来您的Cookie获取方式没有问题；以防万一，也可以参考[文档](http://inside-world.anobaka.com/doc#common-cookie)里Cookie的获取方式

我测试了一下，现在`ExHentai增强器`获取`已保存的Cookie`的方式有点问题，具体表现为：
+ 在程序重启之前，`ExHentai增强器`始终使用的是**程序启动时**的Cookie

该问题预计在`1.6.2-beta3`修复，现在可暂时通过重启程序解决

**Comment by bennyz327** [comment]
重新啟動後可以運作，不會顯示未設定餅乾
但是用了幾個ex下載的本子，分別使用zip包裝和資料夾裸裝當作資源
雖然增強紀錄上的ExHentaiEnhancer顯示打勾完成，但是沒有導入任何標籤和評分數據到資源上
請問有甚麼辦法可以debug嗎?

**Comment by anobaka** [comment]
通过以下方式均可以查询增强情况

+ 【增强记录】
+ 【资源】- 资源封面右上角有个增强记录的图标

因为增强是通过本机发送请求到外部站点，所以可能会跟随网络环境波动。也可能会随着大量访问导致**ip被临时ban**，目前增强一个资源会访问2次：
1. 获取搜索结果
2. 获取第一个资源的详细信息

ExHentai在不同**浏览模式**下搜索返回的html结构不同，之前在 #244 处理过一次，可能会有未考虑到的情况，您可以尝试先设置自己的浏览模式为**Thumbnail**模式，然后重新进行增强。

另：已增强的资源不会被重新增强（包括未找到合适的增强信息），请参考[删除增强记录](http://inside-world.anobaka.com/doc#category-remove-enhancement-records)

**Comment by bennyz327** [comment]
我嘗試將浏览模式設为Thumbnail模式後也重試了好幾次，還是沒有任何錯誤訊息也沒有匯入任何標籤
後來我嘗試重新去F12複製餅乾後，再試了一次，在資源的增強紀錄的頁面就出現錯誤訊息了
(前後兩次使用的cookie值不同格式，之前的是用cookie導出器，尋思問題可能在格式這裡)

第二次cookie值的格式如下:
ipb_member_id=XXX; ipb_pass_hash=XXX; igneous=XXX; sk=XXX
這是遵從您提供的文檔指示複製出來的格式

出現的錯誤訊息如下
`message: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
stacktrace:    at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at Bakabase.InsideWorld.Business.Components.ExHentai.ExHentaiClient.GetHtmlAsync(HttpClient client, String url) in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\ExHentai\ExHentaiClient.cs:line 103
   at Bakabase.InsideWorld.Business.Components.ExHentai.ExHentaiClient.ParseDetail(String cookie, String url) in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\ExHentai\ExHentaiClient.cs:line 216
   at Bakabase.InsideWorld.Business.Components.Resource.Components.Enhancer.ExHentaiEnhancer.Enhance(ResourceDto resource) in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\Resource\Components\Enhancer\ExHentaiEnhancer.cs:line 56
   at Bakabase.InsideWorld.Business.Services.EnhancementRecordService.<>c__DisplayClass25_1.<<_enhance>b__3>d.MoveNext() in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Services\EnhancementRecordService.cs:line 208`

**Comment by anobaka** [comment]
> 我嘗試將浏览模式設为Thumbnail模式後也重試了好幾次，還是沒有任何錯誤訊息也沒有匯入任何標籤
後來我嘗試重新去F12複製餅乾後，再試了一次，在資源的增強紀錄的頁面就出現錯誤訊息了
(前後兩次使用的cookie值不同格式，之前的是用cookie導出器，尋思問題可能在格式這裡)

填写的cookie会直接用于向exhentai发送请求，不会进行任何加工，所以需要填写urlencode之后的cookie，即在F12控制台内通过鼠标拖选后直接复制的cookie（不要通过右键-复制值进行复制）；为了简化验证难度，验证器 #247  已经开发完成，会跟随1.6.2-beta3发布

> message: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set. stacktrace: at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request) at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request) at Bakabase.InsideWorld.Business.Components.ExHentai.ExHentaiClient.GetHtmlAsync(HttpClient client, String url) in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\ExHentai\ExHentaiClient.cs:line 103 at Bakabase.InsideWorld.Business.Components.ExHentai.ExHentaiClient.ParseDetail(String cookie, String url) in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\ExHentai\ExHentaiClient.cs:line 216 at Bakabase.InsideWorld.Business.Components.Resource.Components.Enhancer.ExHentaiEnhancer.Enhance(ResourceDto resource) in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Components\Resource\Components\Enhancer\ExHentaiEnhancer.cs:line 56 at Bakabase.InsideWorld.Business.Services.EnhancementRecordService.<>c__DisplayClass25_1.<<_enhance>b__3>d.MoveNext() in E:\Anobaka\Bakabase.InsideWorld\Bakabase.InsideWorld.Business\Services\EnhancementRecordService.cs:line 208

关于这个问题，可能和前面说的预览模式有关，可能在某些预览模式下未获取到正确的资源详情页的url。

可以麻烦提供一下日志文件（可以从【系统设置】-【日志文件】获取）里`Requesting: `开头的一段吗？`Requesting: `的右边会显示即将请求的url（为方便定位该条日志，这一段日志后面几行内就会出现以上报错的日志，也可以用以上报错信息作为关键字搜索）

**Comment by bennyz327** [comment]
剛剛又試了一次，結果跟之前一樣沒有任何標籤匯入

日誌文件中找了一下，您要是這一段嗎?

`2022-09-19 22:55:43.231 +08:00 [Information] (Bakabase.InsideWorld.Business.Components.ExHentai.ExHentaiClient.) Requesting: https://exhentai.org/?f_search=%5Bremora+works+(CHIPOKAN)%5D+FUTACOLO+CO+-NO+CHARGING-+%5B%E4%B8%AD%E5%9B%BD%E7%BF%BB%E8%A8%B3%5D+%5BDL%E7%89%88%5D
2022-09-19 22:55:44.048 +08:00 [Information] (Microsoft.AspNetCore.Hosting.Diagnostics.GET) Request starting HTTP/1.1 GET http://localhost:12003/updater/app/state?_t=1663599344046 - -
2022-09-19 22:55:44.048 +08:00 [Information] (Microsoft.AspNetCore.Routing.EndpointMiddleware.) Executing endpoint '"Bakabase.InsideWorld.App.Core.Controllers.UpdaterController.GetAppUpdaterStatus (Bakabase.InsideWorld.App.Core)"'
2022-09-19 22:55:44.048 +08:00 [Information] (Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.) Route matched with "{action = \"GetAppUpdaterStatus\", controller = \"Updater\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Bootstrap.Models.ResponseModels.SingletonResponse`1[Bakabase.Infrastructures.Components.App.Upgrade.Abstractions.UpdaterState]] GetAppUpdaterStatus()" on controller "Bakabase.InsideWorld.App.Core.Controllers.UpdaterController" ("Bakabase.InsideWorld.App.Core").
2022-09-19 22:55:44.048 +08:00 [Information] (Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.) Executing "ObjectResult", writing value of type '"Bootstrap.Models.ResponseModels.SingletonResponse`1[[Bakabase.Infrastructures.Components.App.Upgrade.Abstractions.UpdaterState, Bakabase.Infrastructures, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"'.
2022-09-19 22:55:44.048 +08:00 [Information] (Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.) Executed action "Bakabase.InsideWorld.App.Core.Controllers.UpdaterController.GetAppUpdaterStatus (Bakabase.InsideWorld.App.Core)" in 0.1243ms
2022-09-19 22:55:44.048 +08:00 [Information] (Microsoft.AspNetCore.Routing.EndpointMiddleware.) Executed endpoint '"Bakabase.InsideWorld.App.Core.Controllers.UpdaterController.GetAppUpdaterStatus (Bakabase.InsideWorld.App.Core)"'
2022-09-19 22:55:44.049 +08:00 [Information] (Microsoft.AspNetCore.Hosting.Diagnostics.GET) Request finished HTTP/1.1 GET http://localhost:12003/updater/app/state?_t=1663599344046 - - - 200 193 application/json;+charset=utf-8 0.4287ms
2022-09-19 22:55:44.405 +08:00 [Information] (Bakabase.InsideWorld.Business.Components.ExHentai.ExHentaiClient.) Wait 5.00s to request to exhentai. (Cooldown)`

**Comment by anobaka** [comment]
可以找一下`Requesting: `右边不包含`f_search`字符串的url，可能是`空白`，也可能类似`https://exhentai.org/g/xxxxxxx/xxxxxxxx/`

另外可以麻烦发一下您的exhentai的预览模式吗？我试用您的预览模式本地调试一下试试

**Comment by bennyz327** [comment]
這個呢?
> 2022-09-19 23:13:26.290 +08:00 [Information] (Bakabase.InsideWorld.Business.Components.ExHentai.ExHentaiClient.) Requesting: 
2022-09-19 23:13:26.298 +08:00 [Information] (Microsoft.EntityFrameworkCore.Database.Command.) Executed DbCommand ("2"ms) [Parameters=["@p14='1710', @p0='2', @p1='2022-09-19T01:21:02.4180000' (DbType = DateTime), @p2='D:\DL\!處理區歸檔\Mag_test\DB_list\DB3' (Size = 33), @p3='2022-09-19T01:20:52.0000000' (DbType = DateTime), @p4='2022-09-19T01:20:53.0000000' (DbType = DateTime), @p5=NULL, @p6='False', @p7='0', @p8='5', @p9=NULL, @p10='0.0', @p11='[remora works (CHIPOKAN)] FUTACOLO CO -NO CHARGING- [中国翻訳] [DL版]' (Size = 64), @p12=NULL (DbType = DateTime), @p13='2022-09-19T01:21:02.4260000' (DbType = DateTime)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Resources\" SET \"CategoryId\" = @p0, \"CreateDt\" = @p1, \"Directory\" = @p2, \"FileCreateDt\" = @p3, \"FileModifyDt\" = @p4, \"Introduction\" = @p5, \"IsSingleFile\" = @p6, \"Language\" = @p7, \"MediaLibraryId\" = @p8, \"Name\" = @p9, \"Rate\" = @p10, \"RawName\" = @p11, \"ReleaseDt\" = @p12, \"UpdateDt\" = @p13
WHERE \"Id\" = @p14;
SELECT changes();"

**Comment by bennyz327** [comment]
抱歉，聽不太懂甚麼叫做exhentai的预览模式，要如何發呢?
麻煩再詳細解一下~

**Comment by anobaka** [comment]
> 2022-09-19 23:13:26.290 +08:00 [Information] (Bakabase.InsideWorld.Business.Components.ExHentai.ExHentaiClient.) Requesting:

应该是因为浏览模式没完全兼容导致未成功获取资源详情的url

> 抱歉，聽不太懂甚麼叫做exhentai的预览模式，要如何發呢?
Exhentai搜索列表的右上角有一个下拉菜单，里面是 thumbnail、compact等选项，麻烦您发一下您设置了哪个选项，然后我在本机调试一下看看

**Comment by bennyz327** [comment]
我設置的是 thumbnail
![image](https://user-images.githubusercontent.com/96097874/191055879-4c335aa4-2ea3-40fb-8f2c-375e445193c8.png)

**Comment by anobaka** [comment]
收到，我先调试一下，可能需要一段时间，有结果了我直接在这里回复哈

**Comment by anobaka** [comment]
已确认是thumbnail模式下的解析bug，预计在`1.6.2-beta3`修复
