### ISSUE TITLE
[Bug] 点击媒体库/自定义组件触发'/component: [500]'错误

### ISSUE THREAD

**Issue by 2455DD** [anobaka/InsideWorld#530]
点击媒体库/自定义组件时触发'/component: [500]'错误，具体为
> /component: [500]
Value cannot be null. (Parameter Key) 

具体来说，日志中相关记录为
```log
2024-08-29 00:29:01.214 +08:00 [Error] (Bootstrap.Components.Miscellaneous.SimpleExceptionHandlingMiddleware.) DisplayUrl: http://localhost:10001/component?additionalItems=1
Connection: 0HN67FPQIO54D:00000001
ClientIp: ::1
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Bakabase.InsideWorld.Business.Services.ComponentService.ToDtoList(ComponentDescriptor[] descriptors, ComponentDescriptorAdditionalItem additionalItems) in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Services\ComponentService.cs:line 237
   at Bakabase.InsideWorld.Business.Services.ComponentService.GetDescriptorDtoList(Nullable`1 componentType, ComponentDescriptorAdditionalItem additionalItems) in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Services\ComponentService.cs:line 198
   at Bakabase.Service.Controllers.ComponentController.GetDescriptors(Nullable`1 type, ComponentDescriptorAdditionalItem additionalItems) in I:\Code\Anobaka\Bakabase\src\Bakabase.Service\Controllers\ComponentController.cs:line 35
   at lambda_method1006(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Bootstrap.Components.Miscellaneous.SimpleExceptionHandlingMiddleware.Invoke(HttpContext context) in I:\Code\Anobaka\LazyMortal\src\Bootstrap\Components\Miscellaneous\SimpleExceptionHandlingMiddleware.cs:line 34

```

**截屏**
![image](https://github.com/user-attachments/assets/d41f17bc-5872-4b24-a82e-dca3abe4c32f)

**系统:**
 - OS: Windows 11 
 - Version 1.9.0beta

**完整日志**
[AppLog_20240829.log](https://github.com/user-attachments/files/16786374/AppLog_20240829.log)

**Comment by anobaka** [comment]
是移除自定义增强器后对历史数据没有足够的兼容判断导致的，beta2修复
