### ISSUE TITLE
[Bug] 同步媒体库时报错`message: Value cannot be null. (Parameter 'key')`

### ISSUE THREAD

**Issue by 2455DD** [anobaka/InsideWorld#634]
## 复现步骤
选择同步媒体库时报错
使用正则加强器
`^(?<series>[^-]+)-(?<section>[^-]+)-(?<chapter>[^-]+)-(?<theme>[^-]+)(?:[-;](?<tag>[^;.]+);?)*\.(?:mp4|avi|mkv)$`
资源发现使用正则表达式：
`^(?:[^-]+)-(?:[^-]+)-(?:[^-]+)-(?:[^-]+)(?:[-;](?:[^;.]+);?)*\.(?:mp4|avi|mkv)$
`
## 报错内容
```
message: Value cannot be null. (Parameter 'key')
stacktrace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Bakabase.InsideWorld.Business.Services.ResourceService.AddOrPutRange(List`1 resources) in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Services\ResourceService.cs:line 637
   at Bakabase.InsideWorld.Business.Services.ResourceService.AddOrPutRange(List`1 resources) in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Services\ResourceService.cs:line 643
   at Bakabase.InsideWorld.Business.Services.MediaLibraryService.Sync(Int32[] categoryIds, Int32[] mediaLibraryIds, Action`1 onProcessChange, Action`1 onProgressChange) in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Services\MediaLibraryService.cs:line 729
   at Bakabase.InsideWorld.Business.Services.MediaLibraryService.<>c__DisplayClass36_0.<<StartSyncing>b__0>d.MoveNext() in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Services\MediaLibraryService.cs:line 402
--- End of stack trace from previous location ---
   at Bakabase.InsideWorld.Business.Components.Tasks.BackgroundTaskHelper.<>c__DisplayClass7_0`1.<<RunInNewScope>b__0>d.MoveNext() in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Components\Tasks\BackgroundTaskHelper.cs:line 61
--- End of stack trace from previous location ---
   at Bakabase.InsideWorld.Business.Components.Tasks.BackgroundTaskHelper.<>c__DisplayClass7_0`1.<<RunInNewScope>b__0>d.MoveNext() in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Components\Tasks\BackgroundTaskHelper.cs:line 61
--- End of stack trace from previous location ---
   at Bakabase.InsideWorld.Business.Components.Tasks.BackgroundTaskManager.<>c__DisplayClass12_0.<<RunInBackground>b__2>d.MoveNext() in I:\Code\Anobaka\Bakabase\src\legacy\Bakabase.InsideWorld.Business\Components\Tasks\BackgroundTaskManager.cs:line 109
```

**Comment by anobaka** [comment]
媒体库路径配置中如果包含父级资源时会报错
